 #____ _____  _    ____  ____  _   _ ___ ____  
#/ ___|_   _|/ \  |  _ \/ ___|| | | |_ _|  _ \ 
#\___ \ | | / _ \ | |_) \___ \| |_| || || |_) |
 #___) || |/ ___ \|  _ < ___) |  _  || ||  __/ 
#|____/ |_/_/   \_\_| \_\____/|_| |_|___|_|    
                                              

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = " "     # The "symbol" segment is being set to "➜"
error_symbol = ""
use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
